### ISSUE TITLE
Why do some questions have internet sources while others do not?

### ISSUE THREAD

**Issue by wwjCMP** [ItzCrazyKns/Perplexica#102]
And this phenomenon is repeatable, for specific issues there is always a reference to online content, while some issues are never referenced online.

**Comment by ItzCrazyKns** [comment]
The chains and agents are designed in a way that they decide themselves if there is a need for searching the web. If they think it is, they'll search the web and get the answers and tell it to you otherwise they will make up the answers themselves. They search the web if the query is a question like "Who is Elon Musk?" and they won't search the web for "Write an email to my friend..".

**Comment by wwjCMP** [comment]
> The chains and agents are designed in a way that they decide themselves if there is a need for searching the web. If they think it is, they'll search the web and get the answers and tell it to you otherwise they will make up the answers themselves. They search the web if the query is a question like "Who is Elon Musk?" and they won't search the web for "Write an email to my friend..".

Can a feature be added to always search for online content in the future?

**Comment by ItzCrazyKns** [comment]
> > The chains and agents are designed in a way that they decide themselves if there is a need for searching the web. If they think it is, they'll search the web and get the answers and tell it to you otherwise they will make up the answers themselves. They search the web if the query is a question like "Who is Elon Musk?" and they won't search the web for "Write an email to my friend..".
> 
> Can a feature be added to always search for online content in the future?

All the questions except for simple hi, hello are searched online unless it can't understand wether its a question or a writing task
