### ISSUE TITLE
No thumbs up icon in the message response

### ISSUE THREAD

**Issue by arsaboo** [ItzCrazyKns/Perplexica#13]
The message responses currently only show a thumbs-down icon:

![image](https://github.com/ItzCrazyKns/Perplexica/assets/18319734/3d0e462f-c038-4acd-a4d8-31e2ddebd8f6)

We need both thumbs-up and down icon.

**Comment by ItzCrazyKns** [comment]
Hello, Perplexity includes the thumbs-up/down icons because they use that data to fine-tune their models for better responses. Since we don't use this method in Perplexica, we currently do not need the thumbs-up/down icons. However, if we decide to add this capability in the future, we will certainly include it.
