### ISSUE TITLE
Kindly Add API option

### ISSUE THREAD

**Issue by anoobn** [ItzCrazyKns/Perplexica#95]
Hi there,

Since Perplexity and Copilot are free, a web-based interface will help us with testing, but we prefer to have an API option to raise the same to the production level, which can be a game-changer. Kindly add the API option.

**Comment by ItzCrazyKns** [comment]
We don't have any plans for adding an API because it is made to be hosted locally. We might add an API option in the future but for now we're focusing on adding more features and fixing the bugs. Perplexica's backend exposes a WS that you can connect to and make use of. You can understand its structure, working and format by looking into the `websocket` code in the `src` folder.
